name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Check formatting
        run: go fmt ./...
